---
responses:
  - match:
      path: /test/123
      headers:
        X-test: val2
      query:
        action: test
    contentType: application/json
    template: |-
      {"widget": {
          "debug": "on",
          "window": {
              "title": "Sample Konfabulator Widget",
              "name": "main_window",
              "width": 500,
              "height": 500
          },
          "image": {
              "src": "Images/Sun.png",
              "name": "##H#X-mok##",
              "hOffset": 250,
              "vOffset": 250,
              "alignment": "center"
          },
          "text": {
              "data": "Click Here",
              "size": 36,
              "style": "bold",
              "name": "text1",
              "hOffset": 250,
              "vOffset": 100,
              "alignment": "center",
              "onMouseUp": "sun1.opacity = (sun1.opacity / 100) * 90;"
          }
      }}
  - match:
      path: /test/1234
    contentType: application/json
    template: |-
      {"menu": {
          "header": "SVG Viewer",
          "items": [
              {"id": "Open"},
              {"id": "OpenNew", "label": "Open New"},
              null,
              {"id": "ZoomIn", "label": "Zoom In"},
              {"id": "ZoomOut", "label": "Zoom Out"},
              {"id": "OriginalView", "label": "Original View"},
              null,
              {"id": "Quality"},
              {"id": "Pause"},
              {"id": "Mute"},
              null,
              {"id": "Find", "label": "Find..."},
              {"id": "FindAgain", "label": "Find Again"},
              {"id": "Copy"},
              {"id": "CopyAgain", "label": "Copy Again"},
              {"id": "CopySVG", "label": "Copy SVG"},
              {"id": "ViewSVG", "label": "View SVG"},
              {"id": "ViewSource", "label": "View Source"},
              {"id": "SaveAs", "label": "Save As"},
              null,
              {"id": "Help"},
              {"id": "About", "label": "About Adobe CVG Viewer..."}
          ]
      }}
